tsutaj/statements-manager

- .gitignore
- config/default.toml
- config/local_sample.toml
- src/manager/base_manager.py
- src/params_maker/lang_to_class.py
- src/params_maker/languages/cplusplus.py
- src/params_maker/params_maker.py
> add params_maker

- requirements.txt
- src/manager/base_manager.py
- src/params_maker/languages/cplusplus.py
- src/params_maker/params_maker.py
- src/project_file.py
- statements_manager.py
closes #7 
logger 処理を真面目にやった (もう少しエラー処理は必要だが、それは #11 にて行う)
> #7 add logger

- config/docs_sample.toml
- config/interactive_sample.toml
- config/local_sample.toml
- config/sample.toml
- src/config/default.py
- src/config/sample.py
- src/manager/base_manager.py
- src/project_file.py
- statements_manager.py
- `default.toml`, `sample.toml` のモジュール化
- 出力ディレクトリが存在している時の `allow_rewrite = True` のバグ修正
- config のコメント修正
> write default.toml as module

- src/manager/base_manager.py
> #17 add StrictUndefined

- .gitignore
- sample/project.toml
- statements_manager/src/manager/base_manager.py
- statements_manager/template.py
> abolish html template

- statements_manager/main.py
- statements_manager/src/manager/base_manager.py
- statements_manager/src/project.py
> enable to choose extension (md or html)

- setup.py
- 反省: 過去の自分の運用方法を忘れていた
- `feature` ブランチに更新内容をためて、release するときに `feature` を `master` に merge
> v1.4.1-release

- statements_manager/src/variables_converter.py
エスケープ文字を追加して、HTML 生成のバグを修正しました
> Add escape character

- sample/C/problem.toml
- statements_manager/src/variables_converter.py
$-10^{x}$ としたいところが、$-1 \times 10^{x}$ と生成されるバグを修正
> #77 数式生成のバグを修正

- statements_manager/main.py
- `working_dir` を毎回指定するのは面倒
- カレントディレクトリをデフォルトの値として動くようにした (rime と同じ挙動)
> デフォルトの working directory を設定

- statements_manager/src/params_maker/languages/cplusplus.py
- statements_manager/src/params_maker/params_maker.py
- 制約ファイルに #pragma once を記載するようにした
ref: #87
> #87 制約ファイルに #pragma once を記載する

- README.md
- sample/templates/default.html
- sample/templates/icpc_domestic/template.html
- setup.py
- statements_manager/src/manager.py
- statements_manager/src/project.py
- statements_manager/src/renderer.py
- statements_manager/template.py
HTML / PDF 出力には以下の問題があった
- PDF 出力の場合、画像が出力されていなかった
- 添付ファイルを含んだ問題セットの場合、HTML / PDF 出力をすると添付ファイルが正しく出力されていなかった
これらの問題を解消した。
- 問題セットに関するファイルは `WORKING_DIR/problemset` フォルダ内に出力される
- 今までは  `WORKING_DIR` 直下に出力されていたが、添付ファイルが存在することも考慮してフォルダを作成することにしている
- `README` にも反映済み
ref: #89
> HTML / PDF  出力の安定化

- sample/problemset.toml
- sample/templates/default.html
- sample/templates/icpc_domestic/template.html
- statements_manager/src/renderer.py
- statements_manager/template.py
- テンプレートファイルの改修
- Markdown で problemset を作るときに、添付ファイルのパスが置換されない問題の修正
ref: #98
> テンプレートの改修および Markdown 版 problemset のバグ修正

- sample/problemset.toml
- sample/templates/default.html
- sample/templates/icpc_domestic/template.html
- setup.py
- statements_manager/src/renderer.py
- statements_manager/template.py
- Markdown で problemset を出力したときに、添付ファイルのパスが正しくなかった問題の修正
- テンプレートファイルの改修
> v1.6.1-release

- statements_manager/src/manager.py
- statements_manager/src/renderer.py
- statements_manager/src/utils.py
> キャッシュを出力して差分があるかどうかを判定する

- statements_manager/src/manager.py
https://github.com/tsutaj/statements-manager/issues/106#issuecomment-1327304436 のコメントに対応
ref: #106
> ファイルが存在しない場合は常に保存する

- statements_manager/src/variables_converter.py
サンプル入出力のテンプレートで以下を使えるようにした
- `is_first`: 最初のサンプルであるかどうか
- `is_last`: 最後のサンプルであるかどうか
ref: #103
> is_first, is_last 属性の追加

- statements_manager/src/params_maker/params_maker.py
> 差分があったときにしか制約ファイルを更新しないようにする

- docs/examples.rst
> rime clean の使用を促すよう Docs を修正

- sample/templates/sample_default.html
- statements_manager/template.py
HTML を生成していたら気づいたため
一応変更して build して良さげな出力が得られたことは確認しましたが、そこまでちゃんと確認してません（すみません）
> fix h-tag level of sample output

- statements_manager/main.py
- statements_manager/src/manager.py
Closes #126 
credentials file の登録方法を説明した URL の修正
> Fix reg-creds explanation URLs

- statements_manager/src/manager.py
> Do not printing unnessary message on constraints-only mode

- docs/codes/reference/problem.toml
- docs/problem_config.rst
- sample/A/problem.toml
- sample/B/problem.toml
- sample/C/problem.toml
- sample/D/problem.toml
- sample/H/problem.toml
- sample/I/problem.toml
- statements_manager/src/project.py
- statements_manager/src/renderer.py
> New attribute for problem.toml: markdown_extensions

- docs/problemset_config.rst
- statements_manager/src/renderer.py
> Raise error when pre-process or post-process exited abnormally

- .github/workflows/test.yml
- setup.cfg
- tests/test_hello.py
> Create test environment

- .github/workflows/format.yml
- .github/workflows/test.yml
No related ticket
push されたときに job が走らないように修正。pull request 作成時・更新時には行われる。
> Fix CI job triggers

- docs/codes/reference/problem.toml
> Fix docs typo: ignore_samples

- .github/workflows/format.yml
- .github/workflows/test.yml
> Run CI when PR is merged

- statements_manager/src/convert_task_runner.py
- statements_manager/src/execute_config.py
Resolves #137 
実行時に、その ID と関係のない生成物を削除するよう変更しました。
> Remove obsoleted output files

- docs/commands.rst
- statements_manager/src/project.py
#149 
- 変更を追従できていなかった箇所について Docs を修正
- コードの軽微な修正
> Minor fix of docs

- statements_manager/src/utils.py
> Suppress opening browser for reg-creds in order to run in Docker container

- .github/workflows/format.yml
- .gitignore
- tests/test_e2e.py
- tests/test_hello.py
- tests/test_utils.py
Resolves #180 
- テストファイルも format のチェック対象にします。
- テストファイルで format に違反している箇所を修正します。
- 不要なテストファイルを削除します。
> Fix config to format test files

- setup.py
- tests/test_e2e.py
Resolves #182 
E2ETest でファイルの内容に差異があったときに、diff を表示します。
> Show diff on failing E2ETest

- .github/workflows/test.yml
> Run test CI for PRs from fork repositories

- README.md
- statements_manager/main.py
- statements_manager/src/convert_task_runner.py
- statements_manager/src/project.py
#222 
Docs へのリンクを https://docs.tsutaj.com/statements-manager に変更
> Fix path to Docs
